sudo: required
services:
  - docker

before_install:
  - docker build -t brandaser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run brandaser/react-test npm test:ci

after_success:
  - docker build -t brandaser/multi-client ./client
  - docker build -t brandaser/multi-nginx ./nginx
  - docker build -t brandaser/multi-server ./server
  - docker build -t brandaser/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brandaser/multi-client
  - docker push brandaser/multi-nginx
  - docker push brandaser/multi-server
  - docker push brandaser/multi-worker
  #hey
